export const DECREMENT_GLOBAL_LOADING_QUEUE = 'DECREMENT_GLOBAL_LOADING_QUEUE'
export const INCREMENT_GLOBAL_LOADING_QUEUE = 'INCREMENT_GLOBAL_LOADING_QUEUE'
export const UPDATE_DARK_MODE = 'UPDATE_DARK_MODE'
